"""text to token in page model

Revision ID: 443f574d00d4
Revises: 4a1d36fc1905
Create Date: 2026-07-27 07:09:18.920330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f574d00d4'
down_revision = '4a1d36fc1905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
