"""Initial migration

Revision ID: e0ec67c9b361
Revises: 
Create Date: 2026-07-23 12:49:12.548989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ec67c9b361'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_reference_id'), ['reference_id'], unique=True)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('prescription_img', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('services_mentioned', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('patient_instructions', sa.String(length=200), nullable=True),
    sa.Column('durations', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.String(length=200), nullable=True),
    sa.Column('alies_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('platform_id', 'page_id')
    )
    op.create_table('clients',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_bot_message', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id', 'page_id'], ['pages.platform_id', 'pages.page_id'], ),
    sa.PrimaryKeyConstraint('platform_id', 'page_id', 'sender_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('pages')
    op.drop_table('labservices')
    op.drop_table('inquiry')
    op.drop_table('users')
    op.drop_table('request_counter')
    op.drop_table('platforms')
    op.drop_table('laboratory')
    op.drop_table('complaints')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_reference_id'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
