"""rename alies_name to alias_names on labservices

Revision ID: ed4ed324d96b
Revises: e0ec67c9b361
Create Date: 2026-07-23 14:59:16.872929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4ed324d96b'
down_revision = 'e0ec67c9b361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labservices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_names', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specimen', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('search_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('alies_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labservices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alies_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('search_text')
        batch_op.drop_column('specimen')
        batch_op.drop_column('alias_names')

    # ### end Alembic commands ###
